### ISSUE TITLE
사용자가 방향 입력 후 엔터를 눌러야 이동이 실행되는 점 개선

### ISSUE THREAD

**Issue by min942773** [zero5two4/2019_Open_Source#11]
현재 사용자가 방향을 입력하고 엔터를 눌러야 이동이 실행됩니다.
이와 같은 작업은 번거로우므로 엔터를 누르지 않아도 이동되도록 합시다.

**Comment by zero5two4** [comment]
이 문제는 이번 프로젝트 마감까지 해결해야 할 부분은 아니라고 생각됩니다.
