### ISSUE TITLE
Block의 종류에 따라 색깔 다르게 바꾸기

### ISSUE THREAD

**Issue by min942773** [zero5two4/2019_Open_Source#8]
현재는 콘솔창에서 Block간의 큰 차이가 없습니다.
이를 종류에 따라 색을 다르게하여 UI를 개선해야합니다.

**Comment by min942773** [comment]
Issue에 나온 내용 변경을 위한 브랜치 명은
이슈 번호-설명으로 해주시면 감사하겠습니다.

**Comment by zero5two4** [comment]
이 문제는 개선하기 위해서는 표준 함수 범위를 넘어서게 되기 때문에 해결하지 않아도 될 것 같습니다.
